### ISSUE TITLE
User info on translation

### ISSUE THREAD

**Issue by Remo** [concrete5/addon_community_translation#12]
Again, something small and just putting my thoughts out there: We had two cases where someone was over motivated and started to translate a few thing without checking the glossary or the forum or anything. We had to undo most of his changes:
- Search by translator
- See history to get previous translation

We could have downloaded an older PO file, but for those who aren't familiar with git, transifex had a nice solution.

I guess this is quite an edge case, not saying it's a must to have that, just pointing out that this feature was used before.

**Comment by mlocati** [comment]
The translations history is already in place, and opening a translator instance (I mean the online translation page) showing all the translations made by an user is very simple (and is already in my to-do list :wink: )

**Comment by mlocati** [comment]
Community Translation supports two kinds of translators:
- normal translators: they can translate everything, but if a translation is approved they can just submit a suggestion
- reviewers: these users can approve/reject suggestions.

@Remo would it be enough?

**Comment by Remo** [comment]
About translators, yes, but I'm not sure who manages the team. We currently have a few translators who are allowed to add new translators to their language. Either this or the admin has to manage all the teams.

**Comment by mlocati** [comment]
> Either this or the admin has to manage all the teams.

I vote for the first option. Furthermore since CT users will start from scratch, it's a good opportunity to fix the translation teams

**Comment by Remo** [comment]
I'm fine either way, we just have to be aware of the consequences. If we have language managers we have to maek them aware of that fact, an email would be nice to introduce them to the new system, if the admin manages it we need someone that has time to manage them. I know that not all existing language managers would be happy with that though. If someone did most of the work and then the admin approves someone who didn't even read the glossary and destroys the existing translations people get upset.

**Comment by mlocati** [comment]
I don't think that a global administrator for all the languages is a suitable approach: I don't think anybody knows all the 50+ languages we currently have.

Every single translated string of Community Translation has the following properties:

- `current`: every English (source) string may have up to 1 current translation for every language.
- `approved`: a nullable boolean value that holds the approval state of every translation. It can be `true` if the translation is approved, `false` if it's not approved, or `null` if it's waiting for review.

In order to describe this approach, let's talk for instance about the Klingon translation team.
Alice is the Klingon coordinator, and she marks all the current translations as approved.
Let's assume that Bob wants to help translating Klingon: he ask to enter the Klingon translation group.
Alice approves his join request, and Bob becomes a Klingon translator.
Let's talk about the the following cases ([but there are more](https://github.com/concrete5/addon_community_translation/blob/b7e6b0e0628a17e507b7305cdaeace9cdcb750af/src/Translation/Importer.php#L160-L251)):

1. Bob changes the translation of an existing approved string  
Since the previous translation is marked as approved, the current translation is not changed, we keep the approved one, but a notification is sent to Alice telling her that Bob is suggesting a new translation.  
Alice can then approve it (and it'll become the current translation), or reject it.
2. Bob translates a string that previously wasn't translated  
Since there's no current translation, the Bob's one is marked as the current one, but Alice is notified that Bob added a new translation that should be approved.  
Alice is then able to approve the Bob's translation (or again reject it)

What are the problems with this approach?

**Comment by Remo** [comment]
No problem at all, just make sure we aggregate the change notifications, otherwise one might receive a few hundred e-mails ;-) One mail per day would be sufficient

**Comment by mlocati** [comment]
That's what I have in my mind: with the old version of CT the notifications were sent immediately  (so we could have had hundreds of notifications).
With the new version of CT this is no more the case: we store the notifications in a database table (already implemented), and we'll have a CLI commands that aggregates the notifications and delivery them (still to be implemented).
