### ISSUE TITLE
Plural forms place holder variable

### ISSUE THREAD

**Issue by okhayat** [concrete5/addon_community_translation#35]
When translating a string with a countable argument/item, I can't save/approve a translation unless  the place holder in added with each plural form.
This is not suitable for Arabic as the count is excluded when there are 1 or 2 items, and some times with 0 items too.
So, for Zero, One & Two we don't add the count but use a specific expression for it.

Here is an example of files found translation:
Zero - لا يوجد ملفات
One - يوجد ملف واحد
Two - يوجد ملفان
Few - يوجد %s ملفات

I hope the issue is clear and get fixed soon.

**Comment by mlocati** [comment]
That's very clear.

I [added this check](https://github.com/concrete5/addon_community_translation/commit/2de5384614541a37aac5a9cf4aaf5a349310d76b) because often translators don't write correctly the placeholders (for example, they may write `$s` instead of `%s`). That may break the code.

Maybe I can change the code to show a warning instead of an error, so that translators can "force" saving the translation even if the placeholders don't correspond.

Would that work for you?

**Comment by okhayat** [comment]
That would be great!
Thanks.

**Comment by okhayat** [comment]
update?

**Comment by mlocati** [comment]
Fixed by https://github.com/concrete5/addon_community_translation/commit/300c9c80e8bb93d1326231578c4f4e86a6c8b50f (already deployed to https://translate.concrete5.org)
